config/routes.rb
Rails.application.routes.draw do
    root "couriers#index"
    resources :couriers do
        resources :packages
    end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
    has_many :packages
    validates :name, presence: true
    validates :email, presence: true
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier
  validates :tracking_number, presence: true
  validates :delivery_status, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController

    def index
        @couriers=Courier.all
    end

    def show
        @courier=Courier.find(params[:id])
    end

    def new
        @courier=Courier.new
    end

    def create
        @courier=Courier.new(courier_params)
        if @courier.save
            redirect_to @courier
        else
            render :new
        end
    end

    def edit
        @courier=Courier.find(params[:id])
    end

    def update
        @courier=Courier.find(params[:id])
        if @courier.update(courier_params)
            redirect_to @courier
        else
            render :edit
        end
    end

    private
        def courier_params
            params.require(:courier).permit(:name, :email)
        end

end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController

    def create
        @courier=Courier.find(params[:courier_id])
        @package=@courier.packages.create(courier_params)
        redirect_to root_path
    end

    private
        def courier_params
            params.require(:package).permit(:tracking_number, :delivery_status)
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/_form.html.erb
<%= form_with model: courier do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %><br>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/couriers/edit.html.erb
<h1>Edit courier:</h1>
<%= render "form", courier: @courier %>

app/views/couriers/index.html.erb
<br>
<%= link_to "Create New Courier", new_courier_path %>
<h1>Couriers: </h1>
<ul>
<% @couriers.each do |courier| %>
    <li>
    <p>Name:<%= courier.name %></p>
        <ul>
            <li>
                <%= link_to "View courier", courier %>
            </li>
            <li>
                <%= link_to "Edit courier", edit_courier_path(courier) %>
            </li>
        </ul>
    </li>

<% end %>
</ul>

app/views/couriers/new.html.erb
<h1>Courier</h1>

<%= render "form", courier: @courier %>

app/views/couriers/show.html.erb
<h1>Name: <%= @courier.name %></h1>

<p>Email: <%= @courier.email %></p>

<%= form_with model: [@courier, @courier.packages.build] do |form| %>

    <div>
        <p><%= form.label :tracking_number %>:</p>
        <p><%= form.text_field :tracking_number %></p>
    </div>

    <div>
        <p><%= form.label :delivery_status %>:</p>
        <p><%= form.select :delivery_status, [true, false] %></p>
    </div>

    <div>
        <%= form.submit %>
    </div>


<% end %>

<%= link_to "<- All couriers", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>